### ISSUE TITLE
Site indexing strategy

### ISSUE THREAD

**Issue by sjelfull** [sjelfull/craft-supersearch#4]
This feature allows either one index per site or all content in one index (where fields are suffixed with site handle).

- [x] Suffix fields with site handle
- [x] Group elements by target index
- [x] Method for getting index name(s)
- [x] Method for getting index name for specific site
- [x] Check if multisite/suffixing is necessary

**Comment by sjelfull** [comment]
Depends on your needs, essentially. Records are limited by the 10kb limit, so you obviously can't put elements with huge amounts of content multiplied by x sites into the same record.

This option leaves it up to the admin. On some sites it can work with one index, while others prefer to split them out.

I think moving from multi-language (Craft 2) to multi-site (Craft 3) has made me think having the option is good.

**Comment by timkelty** [comment]
Ohhhhhh - are you specifically talking about multi-sites? I thought you were saying everything from Craft would be in 1 index.
